### PR TITLE
Replaced NewtonsoftJson with System.Text.Json, as NewtonsoftJson was …

### PR DESCRIPTION
**Pull request by agustarnason**
…barely used, if at all

### CODE REVIEW

**Review by janid1967 — APPROVED** [review]

**Comment by TordJoranger** [comment]
I have a vague memory that Newtonsoft was needed for JsonPathDocument. Double check that update punch still works

**Review by TordJoranger — CHANGES_REQUESTED** [review]
https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-8.0

**Comment by agustarnason** [comment]
Noted @TordJoranger 
Since it seems like despite the code not showing how NewtonsoftJson is used, it is still required when updating Punch, as such I will close this branch and mark this issue as closed

**Comment by janid1967** [comment]
@agustarnason remove the unmerged branch too

**Pull request closed without merging**
