### PR TITLE
Pbi/103906 deploy completion med radix

### PR DESCRIPTION
**Pull request by arildbjerkenes**
[AB#103906](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/103906)
+
[AB#110041](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/110041)

### CODE REVIEW

**Review by janid1967 — APPROVED** [review]
Approved, with some administrative suggestions:
1. Update PBI 103906 (either comments or description), to reflect that this merge will handle deploy to dev only, without DB migration
1. Add new PBI's to parent of 103906 (which is 100124) for 
   - A: fix migration 
   - B: deploy to test and prod
1. When merging this PR, create a **Merge commit** (don't Squash) so we can see history of commits when continue the work on migration issue

**Review by janid1967 — CHANGES_REQUESTED** [review]
After further considerations with Arild, we agreed to continue working on this branch to fix migration before merge

**Review by janid1967 — APPROVED** [review]

**Comment by janid1967** [comment]
Me and @arildbjerkenes has been co-workers here. He has reviewed my commits

**Comment by arildbjerkenes** [comment]
Changes from Jan Inge is reviewed an approved.

**Pull request merged**
